### ISSUE TITLE
引用模板

### ISSUE THREAD

**Issue by CHENLiver** [mqhe2007/vue-module-loader#1]
import Vue from 'vue'
import App from './App.vue'
import VueRouter from 'vue-router'
import Vuex from 'vuex'
import vueModuleLoader from 'vue-module-loader'
Vue.use(VueRouter)
Vue.use(Vuex)
const router = new VueRouter()
const store = new Vuex.Store()
Vue.use(vueModuleLoader, {
  router, // 合并路由配置必传。
  store // 合并状态配置必传。
})

let app = new Vue({
  router,
  store,
  render: h => h(App, 'vue-module-loader'),
}).$mount('#app')

const  moduleA = require('./admincraft-showcase.umd.js')

app.$moduleLoader(moduleA)
引用后打包后的模板  要怎么在页面上显示出来

**Comment by ChenMo91** [comment]
> import Vue from 'vue'
> import App from './App.vue'
> import VueRouter from 'vue-router'
> import Vuex from 'vuex'
> import vueModuleLoader from 'vue-module-loader'
> Vue.use(VueRouter)
> Vue.use(Vuex)
> const router = new VueRouter()
> const store = new Vuex.Store()
> Vue.use(vueModuleLoader, {
> router, // 合并路由配置必传。
> store // 合并状态配置必传。
> })
> 
> let app = new Vue({
> router,
> store,
> render: h => h(App, 'vue-module-loader'),
> }).$mount('#app')
> 
> const moduleA = require('./admincraft-showcase.umd.js')
> 
> app.$moduleLoader(moduleA)
> 引用后打包后的模板 要怎么在页面上显示出来
请问知道怎么显示了吗？我也没搞出来

**Comment by mqhe2007** [comment]
模块加载时模块的导出函数会被执行，内部逻辑根据个人需要自由发挥，如果有做路由合并，合并后的页面可从路由访问，跟传统vue项目一样。

**Comment by Akira0705** [comment]
> 模块加载时模块的导出函数会被执行，内部逻辑根据个人需要自由发挥，如果有做路由合并，合并后的页面可从路由访问，跟传统vue项目一样。

加载的文件是加载打包出来的 ***.umd.js  就可以了吗。一直没玩懂

**Comment by yushaoyi** [comment]
> 模块加载时模块的导出函数会被执行，内部逻辑根据个人需要自由发挥，如果有做路由合并，合并后的页面可从路由访问，跟传统vue项目一样。

你好，加载完成后如何在当前组件中显示使用这个模块组件呢？

**Comment by mqhe2007** [comment]
> > 模块加载时模块的导出函数会被执行，内部逻辑根据个人需要自由发挥，如果有做路由合并，合并后的页面可从路由访问，跟传统vue项目一样。
> 
> 加载的文件是加载打包出来的 ***.umd.js 就可以了吗。一直没玩懂

对的，文档上关于部署和加载有相关解释。
