### ISSUE TITLE
moduleLoader加载moduleUrl模块失败

### ISSUE THREAD

**Issue by zhengbaofeng** [mqhe2007/vue-module-loader#10]
项目是用vue-module-creator创建的
module文件使用项目内builde:app命令打包，放在本项目public/module文件夹下面

```js
app.$moduleLoader({

  logo: 'http://192.168.31.86:8081/module/logo/myAsync.umd.min.js'

}).then(() => {

  // 加载过程完毕

  console.log('加载完成')

})

app.$mount('#app')
````
使用moduleLoader加载控制台输出加载完毕页面没有相关模块的加载

**Comment by dongkaipo** [comment]
我这边是出现了
`module1 模块加载失败，请检查模块资源是否成功加载。已跳过。`
警告，然后并没有加载远程组件

**Comment by sjhleo** [comment]
我子模块项目是用vue-module-creator创建的
module文件使用项目内builde:module命令打包，放在本项目public/module1文件夹下面，
出现了
module1 模块加载失败，请检查模块资源是否成功加载。已跳过。
警告，然后并没有加载远程组件

**Comment by myseemylife** [comment]
是不是跨域了哦?

**Comment by AlenQi** [comment]
@myseemylife  script 会跨域么

**Comment by mqhe2007** [comment]
模块资源清单中的键要和打包的模块名一致，例如：
```js
{
  myAsync: 'http://192.168.31.86:8081/module/logo/myAsync.umd.min.js'
}
```
