### ISSUE TITLE
vm.$dynamicComponent

### ISSUE THREAD

**Issue by martin-1120** [mqhe2007/vue-module-loader#42]
vm.$dynamicComponent
怎么用？？？使用场景，有没有demo

**Comment by mqhe2007** [comment]
请阅读：https://mqhe2007.github.io/vue-module-loader/api/#vm-dynamiccomponent
如果无法设想使用场景，则您不需要关注这个特性。

**Comment by martin-1120** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by martin-1120** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
