### ISSUE TITLE
官方示例，再vite版本 3.0.0正式版或者3.1.7版本打包module后，再加载，会报错

### ISSUE THREAD

**Issue by EnoND** [mqhe2007/vue-module-loader#51]
vite 3.0.0 正式版以及现在的3.1.7版本  build的 module  会报 TypeError: Cannot read properties of undefined (reading 'name')
应该是  moduleStringFun  执行之后，返回的是 undefined  （moduleDataFromUrl）
而 vml create 示例中 3.0.0-beta.10 的版本是好使的
![image](https://user-images.githubusercontent.com/8067444/195485518-08b4b3f3-573c-4aba-86e5-b7232469088d.png)

**Comment by mqhe2007** [comment]
已修复
